### PR TITLE
Make the repo useful

### PR DESCRIPTION
**Pull request by Zsailer**
Practical steps made:
* organized datasets into datasets folder
* made API for important datasets in Python environments.
* made initial CLI for adding *your* dataset to the list
* CLI for getting a dataset in any format from the list

### CODE REVIEW

**Comment by harmsm** [comment]
Few questions:

+ I'm not sure about the command line interface, at least as written.  Why would a user want to use this?  Is it to get a dataset loaded into a `gpmap` object?  If so, I think we need to make the case as to why `gpmap` is useful.  
+ Did you really break the raw data out into .txt files?  Doesn't seem to be so in the PR -- maybe I'm missing it.  I'm torn about this, but tend to favor the idea of single file/single dataset.  It's easier to keep the datasets intact that way.  I do like the idea of having the json file store the actual observations in a `data` field that contains subfields of genotype, phenotype, etc.  
+ Do we want to make it obvious how a person can contribute to the database on github?

**Comment by Zsailer** [comment]
> * Did you really break the raw data out into .txt files? Doesn't seem to be so in the PR -- maybe I'm missing it. I'm torn about this, but tend to favor the idea of single file/single dataset. It's easier to keep the datasets intact that way. I do like the idea of having the json file store the actual observations in a data field that contains subfields of genotype, phenotype, etc.

No, I think you're looking at the old README? Each dataset is a single JSON file. 

> * I'm not sure about the command line interface, at least as written. Why would a user want to use this? Is it to get a dataset loaded into a gpmap object? If so, I think we need to make the case as to why gpmap is useful.

Yes, the CLI makes it easier to add a dataset -- they don't have to manually "write" JSON files. They can make an excel spreadsheet and have this CLI convert it to JSON and save it to the "datasets" location of this repo (also making it importable, etc.). I need some extra instructions to explain how to submit PR. 

It also let's users "get" the datasets here in a format other than JSON (i.e. Excel/csv). This might be useful if they want to analyze the data in Excel, R, etc.  

It may not be useful. I just figured people are unlikely to use this data if it's *only* in JSON format.

> * Do we want to make it obvious how a person can contribute to the database on github?

Yes, this is definitely still a work in progress. I need to work on the README quite a bit.

**Comment by harmsm** [comment]
Cool, must have been looking at the diff incorrectly or something.  I do like the idea of a json converter program.  The key would be to make sure users know exactly why such code exists via the README.

**Comment by Zsailer** [comment]
I think this is ready to merge. The README needs work, but I think we can iterate. 

One thing to note... this depends on the newest version of `gpmap`. We'll want to merge the newest PR over there, bump the version, and then merge this. 

This PR provides is a list of datasets that can easily be loaded in Python as `GenotypePhenotypeMap` objects.

**Comment by harmsm** [comment]
Sounds like a great plan to me. Thanks for updating.

Mike

**Comment by Zsailer** [comment]
:+1:

**Pull request merged**
